language: node_js
node_js:
- '0.11'
after_script:
- git config --global user.email "tusharmath@gmail.com"
- git config --global user.name "Travis-CI"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
branches:
  only:
  - develop
env:
  global:
    secure: SVMzk44xVPgJpAxUmPDqZlWVmouc19l466/XguOvazyWXJjK/YPu+mypemO3ZfHmYtzuAMJdG/0RK+u2NBTe3LQCuoJwdoOyVNXaahhzKXgl1Z1xzV76/yqkze9Fyf/YoZGnP3ruRIOA5Tv5NgGAQC3WfPd8bAsBb++F+LEr288=
